// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatService 暴露给前端的主服务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

/**
 * AddProject 新建项目。path 必须是已存在的目录。model 为空用默认。
 * @param {string} name
 * @param {string} path
 * @param {string} model
 * @returns {$CancellablePromise<store$0.Project | null>}
 */
export function AddProject(name, path, model) {
    return $Call.ByID(1451936060, name, path, model).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CloseSession 关闭活跃 ACP session(保留 db 记录,可再次 Open)。
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function CloseSession(sessionID) {
    return $Call.ByID(3760278820, sessionID);
}

/**
 * CreateSession 新建 session。git 项目自动建独立 worktree+分支(并行隔离);否则用项目目录。
 * @param {string} projectID
 * @param {string} title
 * @returns {$CancellablePromise<store$0.Session | null>}
 */
export function CreateSession(projectID, title) {
    return $Call.ByID(447560252, projectID, title).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * DeleteSession 删除 session(关闭活跃 harness + 清理 worktree + 删 DB 记录)。
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSession(sessionID) {
    return $Call.ByID(2627033561, sessionID);
}

/**
 * GetConfig 返回当前配置(harness 命令、默认 model、数据目录)。
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetConfig() {
    return $Call.ByID(186762798).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListProjects 列出全部项目。
 * @returns {$CancellablePromise<store$0.Project[]>}
 */
export function ListProjects() {
    return $Call.ByID(3527400214).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ListSessions 列出某项目的全部 session。
 * @param {string} projectID
 * @returns {$CancellablePromise<store$0.Session[]>}
 */
export function ListSessions(projectID) {
    return $Call.ByID(3921381057, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * LoadMessages 取某 session 的全部历史消息(打开 session 时渲染)。
 * @param {string} sessionID
 * @returns {$CancellablePromise<store$0.Message[]>}
 */
export function LoadMessages(sessionID) {
    return $Call.ByID(3750202340, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * MergeSession 把该 session 的分支合并进项目主仓库当前 HEAD(git merge,§orca-style 并行合并)。
 * 冲突时返回 error(含 git 冲突信息),由前端提示用户。
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function MergeSession(sessionID) {
    return $Call.ByID(1693648596, sessionID);
}

/**
 * OpenSession 打开已有 session:有 acp_session_id 则 LoadSession 恢复,否则新建 ACP session(§1.4)。
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function OpenSession(sessionID) {
    return $Call.ByID(844193760, sessionID);
}

/**
 * PickDirectory 弹出原生目录选择对话框,返回选中路径(取消则返回空串)。
 * 供前端「添加项目」时选取项目根目录。
 * @returns {$CancellablePromise<string>}
 */
export function PickDirectory() {
    return $Call.ByID(448240704);
}

/**
 * PickFiles 弹出原生多文件选择对话框,返回选中的文件绝对路径列表(取消则空)。
 * 附件以 @/path 注入 prompt(opencode 据此读取具体文件),供前端 composer 附件功能。
 * @returns {$CancellablePromise<string[]>}
 */
export function PickFiles() {
    return $Call.ByID(1549703512).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * RemoveProject 删除项目(同时关掉其活跃 session)。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveProject(id) {
    return $Call.ByID(1562829465, id);
}

/**
 * RespondPermission 用户在前端对某权限请求做出裁决(§3.4)。
 * @param {string} sessionID
 * @param {string} reqID
 * @param {string} optionID
 * @returns {$CancellablePromise<void>}
 */
export function RespondPermission(sessionID, reqID, optionID) {
    return $Call.ByID(2776607006, sessionID, reqID, optionID);
}

/**
 * SendAndWaitSync 同步发送并等待回复(供驱动/测试用;GUI 用异步 SendMessage)。
 * 返回 agent 文本与错误。失败(peer disconnected)时由调用方重试(下次 ensureLive 会 LoadSession 重连)。
 * @param {string} sessionID
 * @param {string} text
 * @returns {$CancellablePromise<string>}
 */
export function SendAndWaitSync(sessionID, text) {
    return $Call.ByID(1842944601, sessionID, text);
}

/**
 * SendMessage 发送用户消息并驱动 opencode 回复(Prompt,§1.3)。
 * 期间 SessionUpdate 回调并发流入 → 经 event 流式推前端;Prompt 返回后持久化。
 * @param {string} sessionID
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function SendMessage(sessionID, text) {
    return $Call.ByID(320022145, sessionID, text);
}

/**
 * SetDefaultModel 设置全局默认 model(写 settings)。
 * @param {string} model
 * @returns {$CancellablePromise<void>}
 */
export function SetDefaultModel(model) {
    return $Call.ByID(855998230, model);
}

/**
 * StopSession 取消正在进行的 Prompt(用户点「停止」)。
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function StopSession(sessionID) {
    return $Call.ByID(645767144, sessionID);
}

/**
 * UpdateProject 更新项目 name/model。
 * @param {string} id
 * @param {string} name
 * @param {string} model
 * @returns {$CancellablePromise<void>}
 */
export function UpdateProject(id, name, model) {
    return $Call.ByID(1814797502, id, name, model);
}

// Private type creation functions
const $$createType0 = store$0.Project.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = store$0.Session.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = $Create.Array($$createType0);
const $$createType6 = $Create.Array($$createType2);
const $$createType7 = store$0.Message.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($Create.Any);
