// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatService 暴露给前端的主服务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as fsview$0 from "../fsview/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as worktree$0 from "../worktree/models.js";

/**
 * AddProject 新建项目。path 必须是已存在的目录。model 为空用默认。
 * @param {string} name
 * @param {string} path
 * @param {string} model
 * @returns {$CancellablePromise<store$0.Project | null>}
 */
export function AddProject(name, path, model) {
    return $Call.ByID(1451936060, name, path, model).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CloseSession 关闭活跃 ACP session(保留 db 记录,可再次 Open)。
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function CloseSession(sessionID) {
    return $Call.ByID(3760278820, sessionID);
}

/**
 * CreateSession 新建 session。git 项目自动建独立 worktree+分支(并行隔离);否则用项目目录。
 * @param {string} projectID
 * @param {string} title
 * @returns {$CancellablePromise<store$0.Session | null>}
 */
export function CreateSession(projectID, title) {
    return $Call.ByID(447560252, projectID, title).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * DeleteSession 删除 session(关闭活跃 harness + 清理 worktree + 删 DB 记录)。
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSession(sessionID) {
    return $Call.ByID(2627033561, sessionID);
}

/**
 * GetConfig 返回当前配置(harness 命令、默认 model、数据目录)。
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetConfig() {
    return $Call.ByID(186762798).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * InterruptAndSend 打断当前 turn 并立即发送新消息(前端队列面板「立即发送」按钮)。
 * 协议无 queue:turn 进行中发新消息的唯一正确做法 = session/cancel 当前 turn →
 * 等其落定 → 发新 prompt。本方法把这几步原子化(sendMu 保护):
 *   - 置 suppressIdle:本轮 runPrompt 结束时不发 idle(否则前端 auto-continue 会误续发)
 *   - turnCancel:干净 session/cancel(SDK 自动发,非杀进程,连接保持可用)
 *   - <-turnDone:等本轮落定(persist 仍执行,partial 回复不丢)
 *   - startTurn:发新消息(发 prompting)
 * 当前空闲时等价于 SendMessage。其余排队消息由前端持有,本方法不动(用户选「保留其余」)。
 * @param {string} sessionID
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function InterruptAndSend(sessionID, text) {
    return $Call.ByID(820443694, sessionID, text);
}

/**
 * ListProjects 列出全部项目。
 * @returns {$CancellablePromise<store$0.Project[]>}
 */
export function ListProjects() {
    return $Call.ByID(3527400214).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ListSessions 列出某项目的全部 session。
 * @param {string} projectID
 * @returns {$CancellablePromise<store$0.Session[]>}
 */
export function ListSessions(projectID) {
    return $Call.ByID(3921381057, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * LoadMessages 取某 session 的全部历史消息(打开 session 时渲染)。
 * @param {string} sessionID
 * @returns {$CancellablePromise<store$0.Message[]>}
 */
export function LoadMessages(sessionID) {
    return $Call.ByID(3750202340, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * MergeSession 自动提交 session worktree 改动 + 把分支合并进项目主仓库。
 * agent 改了文件但没 commit 也行——AutoCommit 先提交,再 git merge。一键完成,不需命令行。
 * @param {string} sessionID
 * @returns {$CancellablePromise<string>}
 */
export function MergeSession(sessionID) {
    return $Call.ByID(1693648596, sessionID);
}

/**
 * OpenSession 打开已有 session:有 acp_session_id 则 LoadSession 恢复,否则新建 ACP session(§1.4)。
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function OpenSession(sessionID) {
    return $Call.ByID(844193760, sessionID);
}

/**
 * PickDirectory 弹出原生目录选择对话框,返回选中路径(取消则返回空串)。
 * 供前端「添加项目」时选取项目根目录。
 * @returns {$CancellablePromise<string>}
 */
export function PickDirectory() {
    return $Call.ByID(448240704);
}

/**
 * PickFiles 弹出原生多文件选择对话框,返回选中的文件绝对路径列表(取消则空)。
 * 附件以 @/path 注入 prompt(opencode 据此读取具体文件),供前端 composer 附件功能。
 * @returns {$CancellablePromise<string[]>}
 */
export function PickFiles() {
    return $Call.ByID(1549703512).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * RemoveProject 删除项目(同时关掉其活跃 session)。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveProject(id) {
    return $Call.ByID(1562829465, id);
}

/**
 * RespondPermission 用户在前端对某权限请求做出裁决(§3.4)。
 * @param {string} sessionID
 * @param {string} reqID
 * @param {string} optionID
 * @returns {$CancellablePromise<void>}
 */
export function RespondPermission(sessionID, reqID, optionID) {
    return $Call.ByID(2776607006, sessionID, reqID, optionID);
}

/**
 * SendAndWaitSync 同步发送并等待回复(供驱动/测试用;GUI 用异步 SendMessage)。
 * 返回 agent 文本与错误。失败(peer disconnected)时由调用方重试(下次 ensureLive 会 LoadSession 重连)。
 * @param {string} sessionID
 * @param {string} text
 * @returns {$CancellablePromise<string>}
 */
export function SendAndWaitSync(sessionID, text) {
    return $Call.ByID(1842944601, sessionID, text);
}

/**
 * SendMessage 发送用户消息并驱动 opencode 回复(Prompt,§1.3)。
 * 仅在 idle 时可用:协议规定一个 session 同时只允许一个 Prompt(§5.4 调研结论)。
 * turn 进行中时前端应把消息入前端队列(不调本方法);busy 守卫兜底防竞态。
 * @param {string} sessionID
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function SendMessage(sessionID, text) {
    return $Call.ByID(320022145, sessionID, text);
}

/**
 * SessionChanges 返回该 session worktree 的文件级变更列表(VS Code 风格:逐文件 + M/A/D/U 状态)。
 * @param {string} sessionID
 * @returns {$CancellablePromise<worktree$0.FileChange[]>}
 */
export function SessionChanges(sessionID) {
    return $Call.ByID(480190929, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * SessionCommit 提交已暂存的改动(只 commit index,不自动 add)。
 * 提交信息由前端传入,区别于 MergeSession 用 session 标题自动提交。
 * @param {string} sessionID
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function SessionCommit(sessionID, message) {
    return $Call.ByID(3853162461, sessionID, message);
}

/**
 * SessionCreateDir 在 session 工作目录下新建目录。
 * @param {string} sessionID
 * @param {string} rel
 * @returns {$CancellablePromise<void>}
 */
export function SessionCreateDir(sessionID, rel) {
    return $Call.ByID(3508983355, sessionID, rel);
}

/**
 * SessionCreateFile 在 session 工作目录下新建文件(含内容)。
 * @param {string} sessionID
 * @param {string} rel
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SessionCreateFile(sessionID, rel, content) {
    return $Call.ByID(2827924146, sessionID, rel, content);
}

/**
 * SessionDeletePath 删除 session 工作目录下的文件或目录(递归)。
 * @param {string} sessionID
 * @param {string} rel
 * @returns {$CancellablePromise<void>}
 */
export function SessionDeletePath(sessionID, rel) {
    return $Call.ByID(4223657580, sessionID, rel);
}

/**
 * SessionDiff 返回该 session 分支相对主仓库的变更摘要(diff --stat + commit log)。
 * 供前端在分支标签旁展示"这个分支改了什么",让用户决定是否合并。
 * @param {string} sessionID
 * @returns {$CancellablePromise<string>}
 */
export function SessionDiff(sessionID) {
    return $Call.ByID(2727965895, sessionID);
}

/**
 * SessionDiscard 丢弃工作区改动(已跟踪还原 / 未跟踪删除)。只作用于工作区,不动暂存区。
 * @param {string} sessionID
 * @param {string[]} paths
 * @returns {$CancellablePromise<void>}
 */
export function SessionDiscard(sessionID, paths) {
    return $Call.ByID(2948754490, sessionID, paths);
}

/**
 * SessionListDir 列出 session 工作目录下 rel(相对路径)的直接子项。
 * rel 为空表示根。路径钉在 cwd,防越界;git 仓库尊重 .gitignore。
 * @param {string} sessionID
 * @param {string} rel
 * @returns {$CancellablePromise<fsview$0.FileNode[]>}
 */
export function SessionListDir(sessionID, rel) {
    return $Call.ByID(448232447, sessionID, rel).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * SessionReadFile 读取 session 工作目录下 rel 的文本内容(预览用)。
 * @param {string} sessionID
 * @param {string} rel
 * @returns {$CancellablePromise<string>}
 */
export function SessionReadFile(sessionID, rel) {
    return $Call.ByID(3089023042, sessionID, rel);
}

/**
 * SessionRenamePath 把 session 工作目录下的 rel 改名为 newName(叶子名)。
 * 返回新的相对路径。
 * @param {string} sessionID
 * @param {string} rel
 * @param {string} newName
 * @returns {$CancellablePromise<string>}
 */
export function SessionRenamePath(sessionID, rel, newName) {
    return $Call.ByID(3604476385, sessionID, rel, newName);
}

/**
 * SessionStage 暂存文件;paths 为空暂存全部(供源码管理面板,参考 VS Code SCM)。
 * @param {string} sessionID
 * @param {string[]} paths
 * @returns {$CancellablePromise<void>}
 */
export function SessionStage(sessionID, paths) {
    return $Call.ByID(115348126, sessionID, paths);
}

/**
 * SessionUnstage 取消暂存文件;paths 为空取消全部。
 * @param {string} sessionID
 * @param {string[]} paths
 * @returns {$CancellablePromise<void>}
 */
export function SessionUnstage(sessionID, paths) {
    return $Call.ByID(2132742431, sessionID, paths);
}

/**
 * SetDefaultModel 设置全局默认 model(写 settings)。
 * @param {string} model
 * @returns {$CancellablePromise<void>}
 */
export function SetDefaultModel(model) {
    return $Call.ByID(855998230, model);
}

/**
 * StopSession 取消正在进行的 Prompt(用户点「停止」):发干净 session/cancel(非杀进程),
 * harness 与连接保持可用。runPrompt 在 Prompt 返回后推 idle/cancelled,前端据此切回可发送态。
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function StopSession(sessionID) {
    return $Call.ByID(645767144, sessionID);
}

/**
 * ToggleMaximise 双击顶部标题栏时切换窗口最大化/还原(非 fullscreen)。
 * 单窗口桌面应用,取首个窗口。
 * @returns {$CancellablePromise<void>}
 */
export function ToggleMaximise() {
    return $Call.ByID(4042443743);
}

/**
 * UpdateProject 更新项目 name/model。
 * @param {string} id
 * @param {string} name
 * @param {string} model
 * @returns {$CancellablePromise<void>}
 */
export function UpdateProject(id, name, model) {
    return $Call.ByID(1814797502, id, name, model);
}

// Private type creation functions
const $$createType0 = store$0.Project.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = store$0.Session.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = $Create.Array($$createType0);
const $$createType6 = $Create.Array($$createType2);
const $$createType7 = store$0.Message.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = worktree$0.FileChange.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = fsview$0.FileNode.createFrom;
const $$createType13 = $Create.Array($$createType12);
