// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatService 暴露给前端的主服务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as worktree$0 from "../worktree/models.js";

/**
 * AddProject 新建项目。path 必须是已存在的目录。model 为空用默认。
 */
export function AddProject(name: string, path: string, model: string): $CancellablePromise<store$0.Project | null> {
    return $Call.ByID(1451936060, name, path, model);
}

/**
 * CloseSession 关闭活跃 ACP session(保留 db 记录,可再次 Open)。
 */
export function CloseSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3760278820, sessionID);
}

/**
 * CreateSession 新建 session。git 项目自动建独立 worktree+分支(并行隔离);否则用项目目录。
 */
export function CreateSession(projectID: string, title: string): $CancellablePromise<store$0.Session | null> {
    return $Call.ByID(447560252, projectID, title);
}

/**
 * DeleteSession 删除 session(关闭活跃 harness + 清理 worktree + 删 DB 记录)。
 */
export function DeleteSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2627033561, sessionID);
}

/**
 * GetConfig 返回当前配置(harness 命令、默认 model、数据目录)。
 */
export function GetConfig(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(186762798);
}

/**
 * InterruptAndSend 打断当前 turn 并立即发送新消息(前端队列面板「立即发送」按钮)。
 * 协议无 queue:turn 进行中发新消息的唯一正确做法 = session/cancel 当前 turn →
 * 等其落定 → 发新 prompt。本方法把这几步原子化(sendMu 保护):
 *   - 置 suppressIdle:本轮 runPrompt 结束时不发 idle(否则前端 auto-continue 会误续发)
 *   - turnCancel:干净 session/cancel(SDK 自动发,非杀进程,连接保持可用)
 *   - <-turnDone:等本轮落定(persist 仍执行,partial 回复不丢)
 *   - startTurn:发新消息(发 prompting)
 * 当前空闲时等价于 SendMessage。其余排队消息由前端持有,本方法不动(用户选「保留其余」)。
 */
export function InterruptAndSend(sessionID: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(820443694, sessionID, text);
}

/**
 * ListProjects 列出全部项目。
 */
export function ListProjects(): $CancellablePromise<store$0.Project[] | null> {
    return $Call.ByID(3527400214);
}

/**
 * ListSessions 列出某项目的全部 session。
 */
export function ListSessions(projectID: string): $CancellablePromise<store$0.Session[] | null> {
    return $Call.ByID(3921381057, projectID);
}

/**
 * LoadMessages 取某 session 的全部历史消息(打开 session 时渲染)。
 */
export function LoadMessages(sessionID: string): $CancellablePromise<store$0.Message[] | null> {
    return $Call.ByID(3750202340, sessionID);
}

/**
 * MergeSession 自动提交 session worktree 改动 + 把分支合并进项目主仓库。
 * agent 改了文件但没 commit 也行——AutoCommit 先提交,再 git merge。一键完成,不需命令行。
 */
export function MergeSession(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(1693648596, sessionID);
}

/**
 * OpenSession 打开已有 session:有 acp_session_id 则 LoadSession 恢复,否则新建 ACP session(§1.4)。
 */
export function OpenSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(844193760, sessionID);
}

/**
 * PickDirectory 弹出原生目录选择对话框,返回选中路径(取消则返回空串)。
 * 供前端「添加项目」时选取项目根目录。
 */
export function PickDirectory(): $CancellablePromise<string> {
    return $Call.ByID(448240704);
}

/**
 * PickFiles 弹出原生多文件选择对话框,返回选中的文件绝对路径列表(取消则空)。
 * 附件以 @/path 注入 prompt(opencode 据此读取具体文件),供前端 composer 附件功能。
 */
export function PickFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1549703512);
}

/**
 * RemoveProject 删除项目(同时关掉其活跃 session)。
 */
export function RemoveProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(1562829465, id);
}

/**
 * RespondPermission 用户在前端对某权限请求做出裁决(§3.4)。
 */
export function RespondPermission(sessionID: string, reqID: string, optionID: string): $CancellablePromise<void> {
    return $Call.ByID(2776607006, sessionID, reqID, optionID);
}

/**
 * SendAndWaitSync 同步发送并等待回复(供驱动/测试用;GUI 用异步 SendMessage)。
 * 返回 agent 文本与错误。失败(peer disconnected)时由调用方重试(下次 ensureLive 会 LoadSession 重连)。
 */
export function SendAndWaitSync(sessionID: string, text: string): $CancellablePromise<string> {
    return $Call.ByID(1842944601, sessionID, text);
}

/**
 * SendMessage 发送用户消息并驱动 opencode 回复(Prompt,§1.3)。
 * 仅在 idle 时可用:协议规定一个 session 同时只允许一个 Prompt(§5.4 调研结论)。
 * turn 进行中时前端应把消息入前端队列(不调本方法);busy 守卫兜底防竞态。
 */
export function SendMessage(sessionID: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(320022145, sessionID, text);
}

/**
 * SessionChanges 返回该 session worktree 的文件级变更列表(VS Code 风格:逐文件 + M/A/D/U 状态)。
 */
export function SessionChanges(sessionID: string): $CancellablePromise<worktree$0.FileChange[] | null> {
    return $Call.ByID(480190929, sessionID);
}

/**
 * SessionCommit 提交已暂存的改动(只 commit index,不自动 add)。
 * 提交信息由前端传入,区别于 MergeSession 用 session 标题自动提交。
 */
export function SessionCommit(sessionID: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(3853162461, sessionID, message);
}

/**
 * SessionDiff 返回该 session 分支相对主仓库的变更摘要(diff --stat + commit log)。
 * 供前端在分支标签旁展示"这个分支改了什么",让用户决定是否合并。
 */
export function SessionDiff(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(2727965895, sessionID);
}

/**
 * SessionDiscard 丢弃工作区改动(已跟踪还原 / 未跟踪删除)。只作用于工作区,不动暂存区。
 */
export function SessionDiscard(sessionID: string, paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2948754490, sessionID, paths);
}

/**
 * SessionStage 暂存文件;paths 为空暂存全部(供源码管理面板,参考 VS Code SCM)。
 */
export function SessionStage(sessionID: string, paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(115348126, sessionID, paths);
}

/**
 * SessionUnstage 取消暂存文件;paths 为空取消全部。
 */
export function SessionUnstage(sessionID: string, paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2132742431, sessionID, paths);
}

/**
 * SetDefaultModel 设置全局默认 model(写 settings)。
 */
export function SetDefaultModel(model: string): $CancellablePromise<void> {
    return $Call.ByID(855998230, model);
}

/**
 * StopSession 取消正在进行的 Prompt(用户点「停止」):发干净 session/cancel(非杀进程),
 * harness 与连接保持可用。runPrompt 在 Prompt 返回后推 idle/cancelled,前端据此切回可发送态。
 */
export function StopSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(645767144, sessionID);
}

/**
 * ToggleMaximise 双击顶部标题栏时切换窗口最大化/还原(非 fullscreen)。
 * 单窗口桌面应用,取首个窗口。
 */
export function ToggleMaximise(): $CancellablePromise<void> {
    return $Call.ByID(4042443743);
}

/**
 * UpdateProject 更新项目 name/model。
 */
export function UpdateProject(id: string, name: string, model: string): $CancellablePromise<void> {
    return $Call.ByID(1814797502, id, name, model);
}
