// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FileNode 树节点(一层):目录或文件。
 */
export class FileNode {
    /**
     * Creates a new FileNode instance.
     * @param {Partial<FileNode>} [$$source = {}] - The source object to create the FileNode.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * 相对 root 的路径(用 / 分隔,前端原样回传用于展开/操作)
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * 文件字节数
             * @member
             * @type {number | undefined}
             */
            this["size"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileNode}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileNode(/** @type {Partial<FileNode>} */($$parsedSource));
    }
}
