// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Message 一条对话记录(role: user/agent/thought/tool)。
 */
export interface Message {
    "id": string;
    "sessionId": string;
    "role": string;
    "kind": string;
    "content": string;
    "toolCallId"?: string;
    "seq": number;
    "createdAt": number;
}

/**
 * Project 一个项目(= 磁盘目录)。
 */
export interface Project {
    "id": string;
    "name": string;
    "path": string;
    "model": string;
    "createdAt": number;
    "updatedAt": number;
}

/**
 * Session 一个 ACP session(钉在 project 上)。
 */
export interface Session {
    "id": string;
    "projectId": string;
    "acpSession": string;
    "title": string;
    "model": string;

    /**
     * session 的 git worktree 路径(cwd 锚点);空=用项目目录
     */
    "worktreePath": string;

    /**
     * 该 session 对应的 git 分支(merge/清理用)
     */
    "branch": string;
    "createdAt": number;
    "updatedAt": number;
}
