// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileChange 一个文件的变更状态(VS Code 风格)。
 */
export interface FileChange {
    "path": string;

    /**
     * M=修改 A=新增 D=删除 U=未跟踪 R=重命名
     */
    "status": string;
}
