// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FileChange 一个文件的变更状态(VS Code 风格)。
 */
export class FileChange {
    /**
     * Creates a new FileChange instance.
     * @param {Partial<FileChange>} [$$source = {}] - The source object to create the FileChange.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * M=修改 A=新增 D=删除 U=未跟踪 R=重命名
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("staged" in $$source)) {
            /**
             * Staged=true 表示已进暂存区(index 有改动);false 表示工作区改动。
             * 一个文件可能同时出现在两组(如 MM:已暂存后又有新改动),参考 VS Code 的 Changes / Staged Changes 两组。
             * @member
             * @type {boolean}
             */
            this["staged"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileChange instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileChange}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileChange(/** @type {Partial<FileChange>} */($$parsedSource));
    }
}
