// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileChange 一个文件的变更状态(VS Code 风格)。
 */
export interface FileChange {
    "path": string;

    /**
     * M=修改 A=新增 D=删除 U=未跟踪 R=重命名
     */
    "status": string;

    /**
     * Staged=true 表示已进暂存区(index 有改动);false 表示工作区改动。
     * 一个文件可能同时出现在两组(如 MM:已暂存后又有新改动),参考 VS Code 的 Changes / Staged Changes 两组。
     */
    "staged": boolean;
}
